"""Authored scenario judgments, kept separate from reported financial facts."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sources={
'iea': ['IEA • Key Questions on Energy and AI (2026)','https://www.iea.org/reports/key-questions-on-energy-and-ai/executive-summary','2026 report: data-centre electricity consumption is projected to rise from 485 TWh in 2025 to about 950 TWh in 2030. Efficiency, demand, power constraints and financing all affect the outcome. This is an external projection, not an observed 2030 result.'],
'msft':['Microsoft • FY2026 Q4 results','https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q4/press-release-webcast','Azure growth and paid Copilot adoption establish existing monetisation; future returns on infrastructure remain uncertain.'],
'avgo':['Broadcom • FY2026 Q3 results','https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial','The issuer reports growing custom-accelerator and networking sales. Customer concentration and future margins still matter.'],
'snps':['Synopsys • FY2026 Q3 results','https://news.synopsys.com/2026-08-26-Synopsys-Posts-Financial-Results-for-Third-Quarter-Fiscal-Year-2026','EDA and simulation provide AI exposure across competing chip architectures. Acquired Ansys revenue affects reported growth.'],
'j':['Jacobs • FY2026 Q3 results','https://invest.jacobs.com/financials/quarterly-results/default.aspx','Data centres, semiconductors, energy and power contributed to growth. Gross revenue growth exceeded adjusted net revenue growth, an important comparability issue.'],
 'tel':['TE Connectivity • FY2026 Q3 results','https://investors.te.com/news-releases/press-release-details/2026/TE-Connectivity-delivers-results-above-guidance-with-14-sales-growth-and-19-EPS-growth-in-third-quarter-of-fiscal-2026/','The company describes AI momentum in data-centre and energy-infrastructure orders. Its wider portfolio also has non-AI exposure.'],
 'now':['ServiceNow • Q2 2026 results','https://newsroom.servicenow.com/press-releases/details/2026/ServiceNow-Reports-Second-Quarter-2026-Financial-Results/default.aspx','Subscription growth, current remaining obligations and AI workflow products support the adoption thesis; usage must become durable paid business.'],
 'crm':['Salesforce • FY2027 Q2 results','https://www.salesforce.com/news/press-releases/2026/08/26/fy27-q2-earnings/','Agentforce and Data 360 provide a route to AI monetisation. Work-unit activity is not the same as incremental revenue or profit.'],
 'vst':['Vistra • Meta nuclear agreements, January 2026','https://investor.vistracorp.com/2026-01-09-Vistra-and-Meta-Announce-Agreements-to-Support-Nuclear-Plants-in-PJM-and-Add-New-Nuclear-Generation-to-the-Grid','Long-term power agreements support the existing-generation thesis. Some planned uprates extend beyond 2030; they are not assumed to contribute fully within this horizon.'],
 'ceg':['Constellation • Q2 2026 results','https://www.constellationenergy.com/news/2026/08/constellation-reports-second-quarter-2026-results.html','Additional long-term nuclear power contracts demonstrate demand for firm electricity. Contract economics, integration and generation availability remain critical.'],
 'vrt':['Vertiv • Q2 2026 results','https://www.sec.gov/Archives/edgar/data/1674101/000162828026050323/q22026exhibit991vrt07292026.htm','Power and cooling equipment benefit from data-centre construction. The scenario assessment also considers installation delays and order normalisation.'],
 'etn':['Eaton • Q2 2026 results','https://www.eaton.com/de/en-gb/company/news-insights/news-releases/2026/eaton-reports-record-second-quarter-2026-results.html','Electrical orders and backlog provide evidence of demand; conversion to delivered equipment and cash is the key follow-through.'],
 'nvda':['NVIDIA • FY2027 Q2 results','https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027/','Reported accelerator demand supports the buildout thesis. The scenario scores separately consider custom chips, export restrictions and spending cyclicality.'],
 'nvda-risk':['NVIDIA • FY2027 Q2 10-Q','https://investor.nvidia.com/files/doc_financials/2027/NVDA-2027-Q2-10Q-Final-including-exhibits.pdf','The filing identifies power, land, capital, supply commitments and AI-cloud arrangements as relevant risks. A dominant supplier can still be exposed to a capex reversal.'],
 'crwv':['CoreWeave • Q2 2026 results','https://www.sec.gov/Archives/edgar/data/1769628/000176962826000362/coreweave2q26earningspress.htm','Backlog indicates contracted demand, but financing costs, deployment timing and cash spending remain material. Backlog is not current cash profit.'],
 'nbis':['Nebius • Q2 2026 results','https://www.sec.gov/Archives/edgar/data/1513845/000110465926094568/tm2622968d1_ex99-1.htm','The release shows rapid growth alongside significant infrastructure cash investment, and describes financing and power-access risks.'],
 'wday':['Workday • FY2027 Q2 results','https://investor.workday.com/news-and-events/press-releases/news-details/2026/Workday-Announces-Fiscal-2027-Second-Quarter-Financial-Results/default.aspx','AI-related customer expansion provides a possible growth channel. Incumbent distribution does not remove seat-pricing and execution risks.'],
 'adbe':['Adobe • FY2026 Q3 results','https://www.sec.gov/Archives/edgar/data/796343/000079634326000147/adbeex991q326.htm','AI-first recurring revenue is growing. The open question is whether new AI revenue outweighs pressure on incumbent creative subscriptions.'],
 'path':['UiPath • FY2027 Q2 results','https://ir.uipath.com/news/detail/461/uipath-reports-second-quarter-fiscal-2027-financial-results','Automation provides an AI adoption channel, while new agent platforms also create substitution risk.'],
 'ai':['C3.ai • FY2027 Q1 results','https://ir.c3.ai/news-releases/news-release-details/c3-ai-announces-fiscal-first-quarter-2027-results','A turnaround is underway. Latest-quarter cash generation improved, while the trailing-period data still show losses and negative FCF.'],
 'tsm':['TSMC • Q2 2026 presentation','https://www.sec.gov/Archives/edgar/data/1046179/000104617926000451/a2q26presentatione.htm','Advanced manufacturing supports multiple AI chip designers. High-performance computing revenue includes more than AI alone.'],
 'gev':['GE Vernova • Q2 2026 results','https://www.sec.gov/Archives/edgar/data/1996810/000199681026000147/gev2q2026form8-k.pdf','Electrification orders and generation equipment provide exposure to the power bottleneck. Order conversion and project costs can diverge from demand.']
}
scenarios=[
 dict(id='buildout',name='The infrastructure supercycle',short='Buildout',number='01',tagline='Compute demand outruns efficiency gains.',color='#315cec',summary='Agentic work, reasoning and sovereign AI keep expanding. Usage grows faster than cost per task falls, buyers monetise enough demand to keep funding capacity, and grid projects gradually unlock new sites. Scarcity shifts between chips, interconnects and electrical equipment.',assumptions=[['AI infrastructure spending','Illustrative 2030 spend: 1.9–2.4× 2026.'],['Demand versus efficiency','More tasks and more compute per task outweigh falling unit costs.'],['Monetisation','Cloud and AI application revenue support continuing investment.'],['Physical capacity','Grid, packaging and cooling expand, with local shortages persisting.']],path=[100,125,153,185,220],timing=[['2026–27','Existing orders convert; power access and advanced packaging constrain delivery.'],['2028–29','More capacity reaches production; inference and network traffic become larger demand drivers.'],['2030','Watch for overbuilding: scarcity profits can reverse before aggregate AI demand stops growing.']],winners=['NVDA','TSM','VRT','ETN','ANET','GEV'],losers=['AI','INFY','BIDU','INTC'],hiddenPriority=['TEL','J','AVGO','SNPS','VST','CEG'],watch=['Aggregate hyperscaler capex keeps rising alongside AI/cloud revenue, not just management promises.','Electrical orders convert into shipments without worsening receivables or cancellation rates.','HBM and packaging utilisation stay high as new capacity is added.'],invalidate='Two consecutive quarters of broad order cancellations, falling utilisation, or capex rising while AI monetisation stalls would weaken this case.',risk='Strong business growth can still produce poor stock returns if today’s price already assumes more. Supplier scarcity margins and new capacity are cyclical.'),
 dict(id='diffusion',name='Cheaper AI, wider adoption',short='Diffusion',number='02',tagline='Value moves from building AI to using it.',color='#087454',summary='Models become cheaper and more interchangeable. Inference spreads across existing clouds, devices and enterprise workflows. Spending keeps growing more slowly, while distribution, proprietary data, security and custom silicon capture a larger share of value.',assumptions=[['AI infrastructure spending','Illustrative 2030 spend: 1.2–1.6× 2026.'],['Technology','Smaller models, custom chips and better software lower cost per useful task.'],['Enterprise adoption','Customers pay for measurable outcomes; usage grows faster than infrastructure spending.'],['Competitive pressure','Commodity GPU rental and undifferentiated software face lower prices.']],path=[100,112,125,138,150],timing=[['2026–27','Customers test which agents create measurable savings and which tools are interchangeable.'],['2028–29','Inference, data integration and workflow adoption broaden; custom-chip economics matter more.'],['2030','Winners retain customers and capture outcomes revenue even if traditional seat counts fall.']],winners=['AVGO','MSFT','SNPS','NOW','CRM','META'],losers=['CRWV','SMCI','INFY','AI'],hiddenPriority=['NOW','CRM','SNPS','AVGO','TEL','WDAY','MDB','PATH'],watch=['Revenue per AI workload improves after compute costs; token volume alone is insufficient.','Paid renewals, net retention and outcome-based revenue outweigh lost software seats.','Custom accelerators gain useful workloads while data/security spending remains durable.'],invalidate='If efficiency makes AI radically cheaper but customers still will not pay, this shifts toward the reset case. If usage growth overwhelms efficiency, it shifts toward the supercycle.',risk='An incumbent’s customer base is an advantage only if its product remains necessary. Agents can expand software usage and simultaneously undermine per-seat pricing.'),
 dict(id='reset',name='ROI reset & deployment delays',short='Reset',number='03',tagline='Demand exists, but returns and financing disappoint.',color='#a45b30',summary='Power delays, rising depreciation and weak customer economics trigger a multi-year spending pause. Existing AI keeps running, but speculative projects are deferred. Cash-generating incumbents and essential security or maintenance fare relatively better than capacity owners and highly cyclical suppliers.',assumptions=[['AI infrastructure spending','Illustrative trough: 0.75× 2026; recovery to 0.7–1.1× by 2030.'],['Demand and returns','Some workloads grow, but revenue and utilisation disappoint prior plans.'],['Financing','Debt is harder to refinance; dilution and project cancellations become more likely.'],['Bottlenecks','Power delays reduce utilisation; only contracted, economic projects proceed.']],path=[100,80,75,83,95],timing=[['2026–27','Projects slip, working capital rises, and funding costs expose weaker operators.'],['2028–29','Orders reset and hardware prices soften; buyers consolidate vendors around proven use cases.'],['2030','Survivors gain share as spending stabilises. A recovery need not restore prior peak margins.']],winners=['MSFT','IBM','PANW','CRWD','HUBB','TT'],losers=['CRWV','NBIS','ORCL','SMCI','MU','LITE'],hiddenPriority=['MSFT','CRM','WDAY'],watch=['GPU rental prices and utilisation fall together; backlog is renegotiated rather than converted to cash.','Interest, depreciation and capex outgrow operating cash generation.','Grid delays and cancellations spread beyond isolated projects.'],invalidate='Sustained cash returns on new AI capacity, easing power delays and improving financing would undermine the reset. A brief capex pause alone is not enough.',risk='“Winner” here means relatively resilient business positioning. It does not mean rising revenue, a safe share price, or immunity to recession.')
]
# Ratings: relative BUSINESS position within each scenario, never a share-return forecast.
# Each line has ticker | buildout,diffusion,reset | business mechanism | principal risk | evidence to monitor.
catalog='''MSFT|2,3,2|Azure, enterprise distribution and paid copilots link compute to existing customers.|Capex and depreciation can outrun incremental AI cash profit; third-party model economics can shift.|Azure gross margin, paid Copilot renewals and FCF after infrastructure spending.
AMZN|2,3,1|AWS, custom chips and existing customers support inference adoption.|Retail dilutes pure AI exposure; cash spending and cloud price competition can absorb gains.|AWS operating margin, custom-chip adoption and capex-to-OCF conversion.
GOOGL|2,3,1|Cloud, TPUs and consumer distribution can lower the cost of AI delivery.|AI answers can change search-ad economics; investment gains can flatter net income.|Search monetisation, Cloud operating profit and cash investment returns.
META|2,3,1|Recommendation and advertising can monetise AI through an existing auction system.|Frontier-model spending can outgrow advertising gains and introduce depreciation pressure.|Ad conversion, revenue per impression and infrastructure cash returns.
ORCL|2,1,-3|Cloud capacity and enterprise data create a route to AI infrastructure revenue.|Large capacity commitments and negative FCF expose financing and execution risk.|Backlog conversion, financing terms and cash flow after capex and leases.
CRWV|3,-2,-3|Specialist GPU capacity is highly exposed to sustained compute scarcity.|Lower rental prices, customer concentration and financing costs can impair equity economics.|Utilisation, realised GPU pricing, interest expense and contract cash collection.
NBIS|3,-1,-3|New AI cloud capacity can scale rapidly if demand and power access hold.|Expansion requires large cash outlays; share dilution and deployment delays matter.|Energised capacity, customer cash receipts, capex and financing commitments.
AAPL|0,2,2|On-device AI and the installed device base offer an efficiency-led channel.|Useful AI features may not produce a meaningful replacement cycle or pricing premium.|Device upgrades attributable to paid AI value, service retention and margins.
BABA|2,2,0|Cloud and Qwen support domestic AI adoption alongside a large commerce business.|AI investment and commerce competition consume cash; regulation and chip access can constrain growth.|Cloud profit conversion, actual capex and recurring FCF.
BIDU|-1,1,-1|AI cloud and applications could offset pressure on legacy search advertising.|AI growth may fail to replace declining advertising economics and cash investment.|Total group revenue, advertising decline and AI-cloud cash returns.
IBM|1,2,2|Hybrid cloud, enterprise software and implementation connect AI to regulated workloads.|Consulting demand can slow and AI may reduce billable work faster than new services grow.|Software growth, consulting bookings and sustained cash conversion.
DOCN|2,2,-1|Developer distribution can bring AI infrastructure to smaller customers.|Smaller customers are price-sensitive; GPU investment can erode capital-light economics.|Customer retention, GPU contribution margin and cash return on expansion.
NVDA|3,1,-2|Accelerators, software and networking capture a large share of infrastructure demand.|Custom silicon, export constraints, customer financing and supply commitments challenge margins.|Data-centre growth, gross margin, supply commitments and customer utilisation.
AMD|2,2,-2|Alternative GPUs and server CPUs benefit from customers diversifying compute suppliers.|Software adoption and execution may limit share gains; hyperscalers can choose custom chips.|Production deployments, accelerator margins and repeat customer orders.
AVGO|3,3,-1|Custom accelerators and Ethernet silicon can benefit from both scale and lower-cost inference.|A small set of customers can shift designs, bargaining power or schedules.|AI semiconductor sales, design wins and FCF alongside customer concentration.
INTC|-1,1,-2|CPUs and foundry optionality provide exposure beyond leading AI accelerators.|Manufacturing investment and process execution can consume the benefit of demand.|Foundry economics, external production wins and sustainable FCF excluding subsidies.
MU|3,1,-3|HBM and DRAM demand rise with accelerated compute and memory-intensive inference.|Memory pricing and returns can collapse when new supply catches demand.|HBM mix, capacity additions, inventory and cash return across the cycle.
ARM|2,3,0|Efficient CPU designs and royalty exposure benefit from inference and custom systems.|Higher chip volumes do not guarantee better royalty capture; licensing competition remains.|Royalty revenue, data-centre adoption and economics per shipped design.
TSM|3,3,-1|Advanced foundry and packaging serve multiple competing AI chip architectures.|Taiwan concentration, overseas fab costs and heavy investment create non-demand risks.|Leading-node and packaging utilisation, margins and capital intensity.
UMC|1,1,-1|Mature-node and specialty chips support the broader infrastructure electronics bill of materials.|AI exposure is indirect and mature-node overcapacity can dominate the outcome.|Factory utilisation, specialty-node pricing and AI-related design wins.
GFS|1,2,-1|Specialty process technologies can support connectivity, power and edge AI.|Non-AI end markets and fab utilisation can outweigh incremental AI demand.|Specialty demand, utilisation and FCF before grant support.
STM|1,2,-1|Power electronics and embedded chips benefit as intelligence spreads beyond data centres.|Industrial and automotive cycles may dominate; competition can lower prices.|Power-device design wins, inventory normalisation and factory cash returns.
TXN|1,2,0|Analog and power-management chips provide broad exposure to more electrified computing.|Large factory investment and non-AI demand cycles can keep FCF uneven.|Factory utilisation, revenue per end market and capex normalisation.
005930.KS|2,1,-2|Memory and manufacturing give exposure to HBM, DRAM and advanced compute.|Qualification, yields and the memory cycle can overwhelm demand growth.|HBM yields, customer qualifications and recurring operating cash flow.
000660.KS|3,1,-3|HBM is a direct input to high-performance AI systems.|Rapid capacity additions and price normalisation can reverse scarcity returns.|HBM pricing, yields, capital spending and non-operating earnings effects.
ASML|3,2,-1|Lithography enables advanced chips regardless of which designer gains share.|Export restrictions and delayed fab investment can defer equipment revenue.|Leading-edge customer capex, orders, installed-base services and restrictions.
AMAT|3,2,-2|Materials engineering and packaging complexity increase equipment requirements.|Memory and foundry capex are cyclical and export restrictions reduce addressable demand.|Customer capex, packaging orders and service revenue resilience.
LRCX|3,2,-2|Etch and deposition support increasingly complex logic and memory manufacturing.|High exposure to equipment investment means order cuts can be abrupt.|Memory investment, process intensity and service versus equipment mix.
KLAC|3,2,-1|Inspection and process control become more valuable as manufacturing complexity rises.|Fab spending delays still affect equipment orders despite critical technology.|Inspection intensity per wafer, service revenue and customer investment.
TER|2,2,-2|More complex processors and packaging increase semiconductor testing requirements.|Test demand is cyclical and non-AI segments can dilute the benefit.|AI-related test orders, utilisation and concentration among large buyers.
ONTO|3,2,-2|Metrology and packaging inspection support complex AI chips.|Customer concentration and packaging investment timing can make growth uneven.|Advanced-packaging orders, customer diversification and cash conversion.
CAMT|3,2,-2|Inspection tools help improve advanced-packaging yields.|An equipment pause and a small customer base can magnify order volatility.|Packaging inspection demand, repeat orders and fresh interim cash data.
ACLS|0,1,-2|Ion implantation has indirect exposure to semiconductor and power-electronics expansion.|A broad semiconductor recovery is more important than AI demand alone.|Power-device investment and actual AI-linked production orders.
SNPS|2,3,1|EDA, IP and simulation serve competing custom-chip and system designs.|Acquisitions inflate reported growth; integration, debt and export limits can impair returns.|Organic EDA growth, Ansys integration and cash conversion after acquisition costs.
CDNS|2,3,1|Design and simulation tools benefit from more customised, complex AI systems.|Customer R&D budgets, competition and regulatory limits still affect licence demand.|Recurring design-tool revenue, bookings and current cash generation.
ANET|3,2,-1|Ethernet fabrics and switching scale with accelerated-compute clusters.|Large cloud customers and alternative interconnect architectures concentrate risk.|AI Ethernet shipments, customer mix and sustainable margins.
CSCO|1,2,1|Enterprise networks, security and silicon benefit from distributed AI adoption.|Legacy equipment replacement and competition can dilute AI-linked growth.|AI-related bookings converted to revenue and recurring security profitability.
DELL|2,1,-2|AI servers create volume and enterprise deployment opportunities.|High revenue pass-through does not guarantee strong margins or cash generation.|AI-server gross profit, working capital and services attachment.
HPE|2,2,-1|Hybrid infrastructure and networking connect enterprise AI workloads.|Integration costs, thin hardware margins and large deals can delay cash returns.|Networking profitability, backlog quality and operating cash conversion.
SMCI|2,-2,-3|GPU racks and liquid-cooled systems benefit from high deployment volume.|Thin margins, inventory funding and customer concentration can undermine equity returns.|Cash conversion, inventory ageing, margin stability and filing quality.
MRVL|3,3,-2|Custom silicon and optical interconnects are essential to dense AI systems.|Design wins can take years to ramp and large customers can shift suppliers.|Production ramps, customer diversification and margins after development costs.
COHR|3,2,-2|Photonics and transceivers support higher bandwidth between AI systems.|Capital spending, yield execution and pricing competition can constrain FCF.|Optical demand, production yields and positive cash conversion.
LITE|3,2,-3|Optical components benefit from higher AI network bandwidth.|Capacity commitments and volatile accounting earnings add risk to an order downturn.|Cloud optical volumes, recurring operating profit and capacity cash returns.
CIEN|2,2,-1|Data-centre interconnects benefit as AI workloads spread across locations.|Telecom spending and customer concentration can offset cloud demand.|Cloud interconnect orders, carrier demand and margins.
FN|3,2,-1|Precision optical manufacturing benefits from transceiver demand across customers.|Customer concentration, capex and working capital can leave little FCF.|Optical production growth and cash conversion after new capacity investment.
JBL|2,2,0|Manufacturing and engineering provide exposure to data-centre hardware buildout.|Customer concentration and thin margins limit revenue-to-profit conversion.|Data-centre mix, operating margin and cash after working capital.
FLEX|2,2,0|Power and hardware manufacturing support broader AI infrastructure deployment.|Pricing pressure and other industrial markets can dilute AI-related earnings.|Data-centre power revenue, margin and return on incremental capital.
CLS|3,2,-1|Hyperscaler hardware and networking manufacturing benefit from cluster expansion.|Concentrated customers and hardware margins leave sensitivity to order shifts.|Cloud hardware orders, customer diversification and cash conversion.
2317.TW|2,2,-1|AI server assembly adds demand to a very large electronics manufacturing base.|Low margins, customer concentration and non-AI demand reduce pure AI sensitivity.|AI server profit contribution and current operating cash flow.
2382.TW|3,2,-1|Cloud and AI server assembly offer direct buildout exposure.|Assembly revenue can grow faster than profit; primary cash-flow evidence is incomplete.|AI server margins and verified issuer cash-flow statements.
VRT|3,2,-1|Power delivery and liquid cooling are required as rack density rises.|Deferred data centres, competition and working capital can interrupt backlog conversion.|Orders, liquid-cooling mix, shipment conversion and cash generation.
ETN|3,2,1|Switchgear, UPS and electrical distribution address physical deployment constraints.|Capacity additions and execution delays can eventually erode scarcity pricing.|Electrical backlog conversion, incremental margin and cash returns.
GEV|3,2,1|Generation and grid equipment help relieve power constraints.|Long project cycles, execution costs and warranty liabilities can weaken cash returns.|Electrification orders, turbine deliveries and service margins.
PWR|3,2,1|Transmission and grid construction connect growing compute loads.|Permitting, skilled-labour shortages and fixed-price execution can delay profit.|Contracted grid backlog, project conversion and cash collection.
HUBB|2,2,2|Grid components benefit from upgrades also needed outside AI.|Utility budgets and component pricing may soften; NSI integration and acquisition financing add risk.|Utility orders, backlog conversion, NSI integration and debt reduction.
NVT|3,2,1|Enclosures, connections and electrical infrastructure support dense data centres.|Acquisitions and working-capital needs can exaggerate apparent organic momentum.|Organic sales, data-centre mix and acquisition-adjusted cash conversion.
APH|3,3,1|High-speed and power connectors gain content as systems become more complex.|Acquisitions and customer bargaining power complicate organic growth comparisons.|Organic IT-datacom growth, content per system and margins.
SU.PA|3,3,2|Power management and automation support efficient data-centre operation.|Capacity execution and a broad industrial portfolio can dilute AI demand benefits.|Data-centre orders, software/service contribution and cash conversion.
SIE.DE|2,3,2|Electrification, automation and industrial software connect AI to the physical economy.|Long industrial cycles and a diversified portfolio limit direct AI sensitivity.|Electrification orders, digital-software adoption and recurring cash.
ABBN.SW|3,3,2|Electrical distribution and automation address power delivery and efficiency.|Competition and industrial cyclicality can offset data-centre growth.|Electrification orders, margin durability and operating cash returns.
2308.TW|3,3,1|Power conversion and cooling gain importance as rack power density rises.|Customer concentration, pricing and production expansion affect cash conversion.|AI-related power/cooling mix, efficiency gains and factory investment.
CEG|3,1,0|Existing firm generation can secure long-term contracts with data-centre customers.|Outages, regulation, integration and investment needs can absorb contract upside.|Signed contract economics, generation availability and FCF after growth capex.
VST|3,1,0|Existing generation and long-term power agreements capture rising electricity demand.|Hedging, commodity prices and outages may offset gains; some uprates are beyond 2030.|Contract delivery, hedges, maintenance costs and realised cash accretion.
NEE|2,2,1|Utility and renewable capacity support new electricity loads.|Rate regulation, financing and interconnection delays can limit shareholder returns.|Approved rate base, contracted projects and funding needs.
TLN|3,0,-2|Generation near large load centres can benefit from scarce power availability.|Concentrated assets, regulation and commodity exposure increase downside sensitivity.|Contract economics, outage exposure and recurring cash after maintenance.
ETR|2,1,0|New industrial and data-centre load supports regulated grid investment.|Customer concentration and cost allocation can leave utilities with stranded investment.|Binding customer commitments, regulatory recovery and financing requirements.
BE|3,1,-2|On-site generation can address long grid-connection delays.|Project financing, equipment economics and customer credit can overwhelm order growth.|Firm deliveries, service economics and sustained FCF without unusual advances.
TT|2,2,2|Efficient cooling and a broad installed base support equipment and service demand.|Data-centre exposure is only part of the business; construction cycles remain relevant.|Cooling orders, service revenue and cash conversion.
CARR|2,2,1|Chillers and commercial cooling gain from higher data-centre heat loads.|Portfolio changes and broader HVAC demand can dominate reported growth.|Organic commercial cooling growth and updated free cash flow.
JCI|2,2,1|Chillers, controls and building systems improve data-centre efficiency.|Execution and portfolio changes can complicate margins and cash comparisons.|Data-centre order conversion and comparable continuing-operation cash flow.
MOD|3,2,-1|Specialised thermal systems offer concentrated exposure to higher heat density.|Project delays, customer concentration and capacity investment create cyclicality.|Data-centre sales, backlog quality and investment-adjusted cash returns.
EME|3,2,1|Electrical and mechanical construction is needed before AI capacity can operate.|Labour constraints, cancellations and contract execution can erode margins.|Backlog quality, labour productivity and cash collection.
FIX|3,2,-1|Mechanical and electrical contracting benefits from complex facility buildouts.|Construction timing, labour and concentrated projects can reverse strong cash conversion.|Booked work converting to profitable revenue and working-capital normalisation.
ACM|1,2,1|Infrastructure engineering has indirect exposure to power and facility investment.|AI may be small relative to the group; revenue decline can reflect mix and disposals.|Organic net-service revenue, actual AI-linked backlog and margins.
J|2,2,1|Engineering links data centres with power, water and complex facilities.|Gross revenue and acquisitions can overstate organic momentum; project execution matters.|Adjusted net revenue, contracted backlog and operating cash conversion.
EQIX|2,2,0|Colocation and interconnection benefit from distributed enterprise AI workloads.|Power availability, financing and growth capex can absorb earnings; FFO differs from FCF.|Leasing, power delivery, development yields and AFFO alongside cash capex.
DLR|3,1,-1|Large-scale data-centre capacity benefits when customers need powered space.|Unleased capacity, power delays and funding needs make a pause costly.|Preleasing, energised megawatts, development yields and funding terms.
IRM|2,1,-1|Data-centre development supplements a recurring storage business.|New capacity consumes cash and debt capacity before it earns mature returns.|Data-centre leasing, development spending and cash from the legacy business.
PLTR|2,3,-1|Enterprise deployment tools can turn AI experiments into operating workflows.|Strong demand can still disappoint expectations; stock compensation and valuation matter.|Recurring deployments, contract economics and dilution-adjusted cash per share.
SNOW|1,3,-1|Enterprise data infrastructure supports more AI applications and inference.|Compute optimisation and competing data platforms can limit revenue capture.|Consumption growth, retention, operating profitability and dilution.
DDOG|2,3,1|More distributed AI systems need monitoring and observability.|Customers may optimise usage or consolidate tools; spend can be cyclical.|Net retention, AI workload contribution and durable operating margins.
NOW|1,3,1|Workflow ownership creates a route to monetise agents and enterprise automation.|Seat reduction and agent-platform competition may outweigh new paid workloads.|AI renewals, subscription growth, retention and incremental margin.
CRM|1,3,2|Customer data and distribution allow outcome-based AI sales into existing accounts.|Agents can reduce paid seats; activity measures need to translate into cash revenue.|Agentforce recurring revenue, retention and revenue per customer.
ADBE|-1,1,1|Creative workflows and proprietary tools could monetise generative features.|Low-cost generation can substitute for incumbent subscriptions and pressure pricing.|Paid AI conversion, recurring revenue per user and creative subscription retention.
PANW|2,3,2|AI adoption expands security requirements across data, networks and agents.|Platform consolidation and competition can change pricing; acquisitions affect comparability.|Security renewals, organic platform growth and dilution-adjusted FCF.
CRWD|2,3,2|More devices, workloads and automated attacks support security demand.|Execution, competition and stock compensation can limit shareholder capture.|Customer retention, module adoption and recurring GAAP profitability.
NET|2,3,0|Edge infrastructure can distribute low-cost inference and protect AI traffic.|Large cloud platforms can commoditise workloads and pressure developer monetisation.|Paid inference usage, security revenue and cash after network investment.
MDB|1,3,0|Operational data and application development benefit as AI moves into production.|Open-source databases and hyperscaler alternatives can reduce pricing power.|Atlas consumption, AI app retention and durable GAAP operating income.
WDC|2,1,-2|Data creation and retention increase demand for economical bulk storage.|Storage pricing and inventory cycles can dominate AI-related demand.|Cloud storage orders, price per capacity unit and through-cycle cash flow.
SAP|1,3,2|Core enterprise records and workflows provide a distribution point for business AI.|Migration execution and seat-pricing pressure can offset new AI monetisation.|Cloud backlog, paid business-AI adoption and fresh cash-flow statements.
NTAP|1,2,1|Enterprise storage and data management support private and hybrid AI workloads.|Cloud-native alternatives and optimisation can limit incremental storage spend.|AI-linked deployments, subscription growth and recurring cash conversion.
SANM|2,1,-1|Hardware manufacturing participates in infrastructure equipment demand.|Acquisition effects, low margins and customer concentration can overwhelm growth.|Organic infrastructure revenue, working capital and operating margins.
TEL|2,2,1|Power and data connectors gain content as racks and electrical systems become denser.|Transport and industrial cycles can dilute AI gains; stock lag may reflect those risks.|Data-centre orders, organic industrial growth and content per rack.
LFUS|1,2,1|Circuit protection and power control benefit from more electrical infrastructure.|Non-AI demand and impairments can offset the opportunity; positive H1 earnings coexist with a trailing-year loss.|Power-product design wins, organic growth and recurring profit beyond the H1 recovery.
AEIS|3,2,-1|Precision power conversion supports semiconductor equipment and data centres.|Customer concentration and equipment cycles can make growth volatile.|Data-centre power mix, gross margin and cash after capacity expansion.
WDAY|1,2,2|HR and finance workflows provide recurring distribution for enterprise agents.|Fewer employees or reduced seat pricing can offset AI monetisation.|Subscription retention, AI attach rates and revenue per customer.
ZS|1,3,1|Zero-trust security can benefit from more AI-enabled users and workloads.|Persistent GAAP losses, competition and dilution complicate the cash-flow story.|Recurring GAAP earnings, security retention and share-count growth.
PATH|0,2,-1|Automation and orchestration can connect agents to existing business systems.|General-purpose agents may replace parts of the legacy automation product.|Net new recurring revenue, agent usage paid conversion and renewal rates.
AI|-2,-1,-2|Enterprise AI applications offer turnaround optionality if deployments become repeatable.|Revenue contraction, losses and a competitive platform market make execution decisive.|Sustained revenue recovery and multiple quarters of positive cash generation.
INFY|-2,-2,0|Enterprise implementation work can grow as AI spreads across clients.|Automation can reduce billable hours faster than new AI projects replace them.|AI deal revenue, pricing per outcome and margins as employee effort falls.'''
profiles={}
for line in catalog.splitlines():
 t,s,m,r,w=line.split('|')
 profiles[t]=dict(scores=list(map(int,s.split(','))),mechanism=m,risk=r,watch=w,sources=[])
for key,tickers in {'msft':['MSFT'],'avgo':['AVGO'],'snps':['SNPS'],'j':['J'],'tel':['TEL'],'now':['NOW'],'crm':['CRM'],'vst':['VST'],'ceg':['CEG'],'vrt':['VRT'],'etn':['ETN'],'nvda':['NVDA'],'nvda-risk':['NVDA'],'crwv':['CRWV'],'nbis':['NBIS'],'wday':['WDAY'],'adbe':['ADBE'],'path':['PATH'],'ai':['AI'],'tsm':['TSM'],'gev':['GEV']}.items():
 for t in tickers:profiles[t]['sources'].append(key)
# Deep dives state how the same company changes across the three paths.
deep={
'TEL':['More electrical and high-speed content per system creates a less obvious supplier channel. Its diversified exposure makes the thesis less explosive than a pure AI hardware bet.','Connectivity remains necessary even when the winning compute architecture changes. Efficiency can increase adoption, but lower spend per system limits the upside.','Diversification offers a cushion, not immunity. Industrial weakness and delayed orders can outweigh AI content gains.'],
'J':['Engineering is required before new data centres can operate; power and water complexity increases the value of project expertise.','Retrofitting and more distributed infrastructure can keep design work relevant even if the biggest new builds slow.','A broad infrastructure portfolio can help, but exposed projects can still be postponed. It is a moderate relative-resilience thesis.'],
'AVGO':['Custom accelerators and networking participate directly in expanding hyperscaler capacity. Positive FCF and a lagging one-year share return justify further research.','More specialised inference favours cost-efficient custom silicon. This is a stronger strategic fit than assuming all compute remains on merchant GPUs.','Large customers may delay projects, and networking growth can slow. Software cash flow is a cushion; it does not make semiconductor demand defensive.'],
'SNPS':['More chip programmes and complex systems support EDA and simulation demand across suppliers. Separate organic growth from the Ansys acquisition.','Custom silicon proliferating across clouds and devices increases the number of designs. Selling design tools avoids choosing a single winning chip architecture.','Design R&D may prove stickier than factory equipment spending, but budgets and integration costs still matter. Relative resilience is only moderate.'],
'VST':['Firm generation has value when power limits new compute capacity. Existing signed contracts support the thesis more than speculative nuclear projects.','Lower energy per task may restrain power scarcity rents. Demand still exists, but the business loses some relative advantage versus software and custom chips.','Lower expected load and commodity prices can reduce upside; contracts and hedging may cushion it. Do not assume every megawatt is repriced immediately.'],
'CEG':['Operating generation and signed power contracts offer near-term relevance. Restart and integration costs must be assessed against actual cash returns.','Efficiency moderates the most aggressive power-demand expectations. Firm power is useful, but this is a smaller relative beneficiary.','Existing contracts may protect some cash flows while weaker pricing and funding costs weigh on new projects. Earnings resilience is contract-specific.'],
'NOW':['Workflow adoption benefits, but much incremental spending first flows to physical infrastructure. Hardware growth does not automatically translate to software pricing power.','Agent deployment inside existing enterprise workflows is a direct monetisation channel. The test is paid renewal and incremental profit, not demonstrations or user counts.','Customers may favour existing strategic platforms, but deferred expansions and fewer seats can offset savings-led adoption. Only a modest relative advantage is assigned.'],
'CRM':['Its AI opportunity grows with enterprise adoption, but this scenario disproportionately rewards capacity suppliers.','Agentforce and customer data can support outcome-based revenue. It qualifies only if new economics exceed the loss of traditional seats.','Existing customers, cash generation and measurable cost-saving use cases make a relative-resilience case. Revenue can still slow and the share price can still fall.'],
'WDAY':['A gradual enterprise beneficiary; less direct exposure to the capacity wave than chips and power.','Trusted HR and finance data can support agents in high-value workflows. Lower seat counts are the counterweight.','Recurring core systems and cost-saving automation may be harder to cut than experimental AI projects. This does not eliminate hiring sensitivity.'],
'MSFT':['Cloud capacity and enterprise monetisation create a broad beneficiary, with cash returns dependent on exceptionally large investment.','Cheaper models plus distribution can expand adoption and improve economics. The case needs revenue growth that survives price competition.','Existing profitable businesses offer relative resilience versus debt-dependent new capacity providers. Depreciation and capex commitments are still real headwinds.'],
'ADBE':['Infrastructure expansion is not a direct monetisation benefit; new models can pressure the creative-software franchise.','Cheaper generation creates both new products and substitution. Positive profit and a falling stock are insufficient without evidence of paid retention.','Cash generation may cushion slower demand, but product substitution can continue even during an investment reset. Not a clean defensive winner.'],
'CRWV':['High capacity demand could support rapid growth, but the equity case depends on contract quality, financing costs and cash conversion.','Cheaper compute and more provider choice risk compressing rental returns while fixed obligations remain.','A utilisation and funding shock creates a particularly adverse combination. A large backlog cannot be treated as unrestricted cash.'],
'PLTR':['Enterprise deployments benefit, though investment is concentrated upstream.','Helping organisations deploy AI can be a strong business position. Passing a relative-price screen does not make a widely followed stock cheap.','Procurement slows and customers scrutinise pricing. A resilient product can still carry high expectations that reset.'],
'INFY':['Clients directing budgets into infrastructure may restrain services spend while automation reduces labour demand.','AI implementation opportunities compete with fewer billable hours. The outcome depends on capturing productivity gains through pricing.','Established client relationships and efficiency services may cushion a slowdown, but this is neutral rather than a confident growth winner.']
}
deep.update({
'NVDA':['Training and inference growth keep accelerator clusters and their networking in demand. Software and system integration can sustain pricing power, but this assumes customers earn enough to fund the next generation.','Usage can rise while spending per task falls. Custom chips take repeatable workloads; the software ecosystem keeps NVIDIA relevant, but it is a less direct beneficiary of commoditisation.','A pause in new clusters reduces orders while supply commitments and product transitions remain. Installed usage can keep growing even as new hardware margins and stock expectations fall.'],
'TSM':['Leading-edge fabrication and advanced packaging earn revenue regardless of which major designer wins. The bottleneck is profitable capacity conversion, not simply more announced fab investment.','More custom designs widen the customer opportunity and efficient chips still need sophisticated manufacturing. Architecture diversity helps; lower selling prices and overseas fab costs can offset volumes.','Customer inventory corrections reduce utilisation and operating leverage. Its strategic position can survive while earnings and cash returns weaken during the pause.'],
'VRT':['Rising rack density increases the need for power conditioning and heat removal. The strongest case is installed equipment and service cash, with backlog converting on schedule.','Inference expands into a wider footprint, supporting cooling and electrical upgrades. Efficiency reduces equipment spend per task, making mix and installed-base service more important.','New-site delays hit equipment deliveries and working capital. Maintenance of live facilities provides a cushion, but does not replace a large decline in new capacity orders.'],
'ETN':['Electrical distribution and protection sit on the critical path between a funded data centre and an operating one. Scarce qualified equipment can support pricing until capacity catches up.','Distributed workloads and electrification retain a need for electrical equipment. A wider customer base can offset less extreme AI spending, provided order margins hold.','Utility replacement and general electrification offer demand beyond AI. Project delays and weaker scarcity pricing still limit growth, so only a modest advantage is assigned.'],
'ANET':['Larger clusters need high-speed switching and fabrics. Winning the relevant Ethernet deployments matters more than total AI traffic alone.','Lower-cost, distributed inference can expand networking needs and favour interoperable infrastructure. Competition and customer bargaining determine how much value reaches margins.','Cloud customers can extend replacement cycles and defer cluster orders. Existing network traffic does not guarantee continued hardware purchases at peak growth rates.'],
'GEV':['Grid and generation equipment address the power constraint that prevents compute assets from earning revenue. Long lead times create opportunity but also execution and cost risk.','Moderating power intensity reduces the most aggressive demand forecasts. Grid upgrades and non-AI generation needs can still support orders and services.','Large projects face financing and scheduling pressure. Equipment services and grid replacement are cushions; new generation orders can reset well before installations peak.'],
'META':['Better ad targeting can monetise AI immediately through its existing platform. The constraint is whether incremental ad cash exceeds frontier-model and infrastructure spending.','Lower inference costs improve the economics of recommendations, ads and user tools. Distribution is valuable if engagement and advertiser returns improve without equally large cost increases.','A strong core ad business can absorb some investment retrenchment. Advertising remains cyclical, and long-lived infrastructure commitments may outlast weaker demand.'],
'IBM':['Hybrid infrastructure and implementation capture some spending, but do not have the same direct scarcity exposure as accelerators or electrical equipment.','Regulated enterprises need integration, governance and deployment across existing systems. Software adoption must outweigh automation pressure on consulting effort.','Customers retain essential enterprise systems and may buy efficiency projects. Consulting can still slow; this is a relative cash-generation thesis rather than immunity from cuts.'],
'PANW':['More infrastructure and connected workloads expand the security surface. Security monetisation depends on paid platform adoption rather than raw compute purchases.','Cheaper AI widens adoption and attack capability, supporting consolidated security platforms. Customer retention and profitable cross-selling are the key tests.','Security is harder to defer than speculative capacity when existing systems remain exposed. Vendor consolidation can help leading platforms, although budgets and multiples can contract.'],
'CRWD':['Additional cloud workloads and endpoints support demand, although most capex first goes to infrastructure suppliers.','Agents add identities, workloads and security complexity. A broad security platform can capture recurring spend if execution and retention remain strong.','Protection of existing operations continues even when new AI projects stop. Stock compensation, competition and execution prevent treating business resilience as guaranteed equity upside.'],
'HUBB':['Grid hardware and electrical components connect new load to the network. Organic demand and acquisition integration both determine the cash benefit.','A broader footprint of inference still requires grid upgrades. Component demand also comes from non-AI replacement and electrification.','Maintenance and replacement spending can be more durable than speculative data-centre starts. Utility budgets and acquisition debt remain important limits to the defensive case.'],
'TT':['More cooling demand expands the opportunity, but broader commercial HVAC limits its sensitivity to an AI-only supercycle.','Efficient cooling and a wider installed base support equipment and services. Value depends on energy savings that customers will actually pay for.','Service and replacement needs on operating buildings remain. New construction and large projects can weaken; resilience comes from the installed base, not immunity to recession.'],
'NBIS':['Rapid capacity deployment can turn contracted demand into revenue. Energised sites, cash collections and financing terms matter more than the size of announced commitments.','Cloud customers gain more supply choices and lower compute prices. Growth may remain high while returns on new capacity become less attractive.','New capacity requires funding before generating cash. Delays and lower utilisation can combine with dilution or refinancing pressure, creating a severe headwind.'],
'ORCL':['Enterprise data relationships and contracted cloud demand offer large growth potential. Funding and delivering capacity on economic terms determine whether that demand creates shareholder value.','Existing databases and customer relationships support inference, but lower capacity pricing can offset volume growth. This is a mixed case, not an automatic software winner.','Heavy infrastructure obligations and cash investment become harder to support as utilisation and customer returns disappoint. Backlog does not eliminate financing or counterparty risk.'],
'SMCI':['Fast deployment of AI servers can support volumes, but assembly competition and working capital limit how much of the capex boom becomes free cash flow.','More efficient workloads can need fewer high-end systems per unit of useful output. Buyers can bargain harder as hardware becomes more interchangeable.','Deferred orders and falling component prices expose inventory and working-capital risk. A server integrator can lose cash even if end-user AI consumption keeps rising.'],
'MU':['HBM and DRAM demand support favourable mix and pricing while supply is constrained. The risk arrives when capacity additions exceed sustainable demand.','Memory remains necessary for inference, but efficiency and new supply can moderate pricing. Higher bit demand alone is insufficient for durable profit growth.','Lower utilisation and excess supply can produce a sharp memory-price correction. High fixed costs make earnings especially sensitive to the investment cycle.'],
'LITE':['More high-speed optical links create a direct demand channel. Product mix and cash conversion determine whether higher shipments overcome reported earnings weakness.','Network traffic still grows, but competition and architecture changes can limit pricing. Design wins matter more than extrapolating industry bandwidth growth.','Delayed optical deployments and customer concentration amplify a capex slowdown. Orders, inventory and financing need scrutiny alongside large reported net losses.'],
'MDB':['AI applications need operational data, but the early spending wave can favour capacity providers before database consumption catches up.','More applications and retrieval workflows can increase paid database consumption. The advantage depends on retaining developers against hyperscaler and open-source alternatives.','Consumption can slow quickly when customers optimise workloads. Existing applications provide a base, but the scenario offers only a modest advantage.'],
'PATH':['More compute does not itself create demand for a specific automation platform. Commercial adoption and renewal economics must catch up with the infrastructure wave.','Agents can use existing automation and orchestration to act inside enterprise systems. They can also replace older automation; paid retention is the decisive counterargument to the hidden-candidate screen.','Customers may cut experimental automation while keeping essential processes. Product substitution and slower new deals make the reset a modest headwind.'],
'AI':['The spending boom can bypass application vendors that have not achieved repeatable profitable deployment. An operational turnaround matters more than industry demand headlines.','Broader adoption creates opportunity, but customers can choose established platforms or build with cheaper models. Recent cash improvement must become recurring revenue and profit.','Long sales cycles and tighter discretionary budgets make a turnaround harder. Losses reduce room to fund growth while customers demand faster payback.']
})
for t,p in profiles.items():
 p['scenarioNotes']=deep.get(t,[])
 p['evidenceLevel']='Linked issuer context' if p['sources'] else 'Business-model inference'
# No priors or price targets are invented. The spend curves are explicit illustrative assumptions.
result=dict(asOf='2026-10-03',horizon='2030-12-31',scenarios=scenarios,profiles=profiles,sources={k:dict(title=v[0],url=v[1],note=v[2]) for k,v in sources.items()},ratingLabels={'-3':'Severe headwind','-2':'Headwind','-1':'Modest headwind','0':'Balanced / uncertain','1':'Modest advantage','2':'Advantage','3':'Strong advantage'})
assert len(profiles)==100,len(profiles)
base=json.loads((ROOT/'dist/data.json').read_text())
assert set(profiles)=={c['ticker'] for c in base['companies']}
(ROOT/'dist/scenarios.json').write_text(json.dumps(result,ensure_ascii=False,indent=2))
print('Scenario coverage:',len(profiles),'companies ×',len(scenarios),'scenarios; sources:',len(sources))
