GROUPS = {
'Cloud & platforms': [('MSFT','Microsoft','Azure cloud and enterprise AI distribution'),('AMZN','Amazon','AWS compute, custom silicon and AI services'),('GOOGL','Alphabet','Google Cloud, Gemini and TPU infrastructure'),('META','Meta','Large AI infrastructure buyer; advertising monetization'),('ORCL','Oracle','Cloud infrastructure and AI database workloads'),('CRWV','CoreWeave','GPU cloud capacity for AI developers'),('NBIS','Nebius','AI cloud infrastructure'),('AAPL','Apple','AI-enabled devices and on-device compute'),('BABA','Alibaba','Cloud infrastructure and AI models in China'),('BIDU','Baidu','AI cloud and model services in China'),('IBM','IBM','Enterprise AI software, infrastructure and services'),('DOCN','DigitalOcean','Developer cloud and GPU infrastructure')],
'Chips & memory':[('NVDA','NVIDIA','AI accelerators, networking and compute systems'),('AMD','AMD','Data-center GPUs and server CPUs'),('AVGO','Broadcom','Custom AI accelerators and networking silicon'),('INTC','Intel','Server CPUs and semiconductor manufacturing'),('MU','Micron','High-bandwidth memory and DRAM'),('ARM','Arm','Processor architecture and IP licensing'),('TSM','TSMC','Advanced-node foundry and chip packaging'),('UMC','UMC','Specialty and mature-node foundry'),('GFS','GlobalFoundries','Specialty semiconductor manufacturing'),('STM','STMicroelectronics','Power management and embedded silicon'),('TXN','Texas Instruments','Analog and power-management chips'),('005930.KS','Samsung Electronics','Memory, high-bandwidth memory and foundry'),('000660.KS','SK hynix','High-bandwidth memory for AI accelerators')],
'Chipmaking & design':[('ASML','ASML','Lithography equipment for advanced chips'),('AMAT','Applied Materials','Deposition, materials engineering and packaging equipment'),('LRCX','Lam Research','Etch and deposition equipment'),('KLAC','KLA','Wafer inspection and process control'),('TER','Teradyne','Semiconductor test equipment'),('ONTO','Onto Innovation','Metrology and advanced-packaging inspection'),('CAMT','Camtek','Inspection and metrology for advanced packaging'),('ACLS','Axcelis','Ion implantation systems'),('SNPS','Synopsys','Chip design software and semiconductor IP'),('CDNS','Cadence','Chip design and system simulation software')],
'Networking & servers':[('ANET','Arista Networks','Data-center Ethernet switching'),('CSCO','Cisco','Networking systems, optics and silicon'),('DELL','Dell Technologies','AI servers and enterprise infrastructure'),('HPE','Hewlett Packard Enterprise','AI systems, servers and networking'),('SMCI','Super Micro Computer','GPU servers and liquid-cooled racks'),('MRVL','Marvell','Custom silicon, interconnects and optical DSPs'),('COHR','Coherent','Optical transceivers and photonics'),('LITE','Lumentum','Optical components and cloud interconnects'),('CIEN','Ciena','Optical networking and data-center interconnects'),('FN','Fabrinet','Optical manufacturing services'),('JBL','Jabil','Electronics and data-center hardware manufacturing'),('FLEX','Flex','Data-center equipment and power manufacturing'),('CLS','Celestica','Networking and hyperscaler hardware manufacturing'),('2317.TW','Hon Hai / Foxconn','AI server assembly and electronics manufacturing'),('2382.TW','Quanta Computer','AI servers and cloud hardware manufacturing')],
'Power & grid':[('VRT','Vertiv','Data-center power and thermal-management systems'),('ETN','Eaton','Switchgear, UPS and electrical distribution'),('GEV','GE Vernova','Gas generation equipment and grid electrification'),('PWR','Quanta Services','Grid transmission and electrical construction'),('HUBB','Hubbell','Utility and electrical infrastructure components'),('NVT','nVent','Electrical enclosures and connection systems'),('APH','Amphenol','High-speed connectors and interconnects'),('SU.PA','Schneider Electric','Power distribution and data-center energy management'),('SIE.DE','Siemens','Electrical infrastructure and industrial automation'),('ABBN.SW','ABB','Electrification, switchgear and power distribution'),('2308.TW','Delta Electronics','Power supplies and data-center cooling')],
'Energy supply':[('CEG','Constellation Energy','Nuclear generation and electricity supply'),('VST','Vistra','Power generation and retail electricity'),('NEE','NextEra Energy','Utility capacity and renewable generation'),('TLN','Talen Energy','Power generation serving growing electricity demand'),('ETR','Entergy','Utility generation and grid capacity'),('BE','Bloom Energy','On-site fuel-cell power systems')],
'Cooling & construction':[('TT','Trane Technologies','Chillers and data-center thermal systems'),('CARR','Carrier','Commercial cooling and HVAC equipment'),('JCI','Johnson Controls','Chillers and building systems'),('MOD','Modine','Data-center cooling systems'),('EME','EMCOR','Electrical and mechanical construction'),('FIX','Comfort Systems USA','Mechanical and electrical contracting'),('ACM','AECOM','Engineering and infrastructure design'),('J','Jacobs','Engineering for advanced facilities')],
'Data centers':[('EQIX','Equinix','Colocation and interconnection facilities'),('DLR','Digital Realty','Data-center real estate and capacity'),('IRM','Iron Mountain','Data-center development and colocation')],
'Software & applications':[('PLTR','Palantir','Enterprise AI deployment and analytics'),('SNOW','Snowflake','Cloud data infrastructure and AI tools'),('DDOG','Datadog','Observability for cloud and AI workloads'),('NOW','ServiceNow','Enterprise workflow automation and AI agents'),('CRM','Salesforce','Customer-management software and AI agents'),('ADBE','Adobe','Creative software and generative AI tools'),('PANW','Palo Alto Networks','Cybersecurity for cloud and AI environments'),('CRWD','CrowdStrike','Cloud security and AI-assisted threat detection'),('NET','Cloudflare','Edge networks, AI inference and developer services'),('MDB','MongoDB','Operational databases and AI application data'),('WDC','Western Digital','Data-center hard drives and storage infrastructure'),('SAP','SAP','Enterprise business software and AI integration')]
}
ROSTER=[dict(ticker=t,name=n,role=r,sector=s) for s,rows in GROUPS.items() for t,n,r in rows]
for sector, rows in {
'Networking & servers':[('NTAP','NetApp','Enterprise storage for data and AI workloads'),('SANM','Sanmina','Communications and computing hardware manufacturing')],
'Power & grid':[('TEL','TE Connectivity','Electrical and high-speed data connectors'),('LFUS','Littelfuse','Circuit protection and power-control components'),('AEIS','Advanced Energy','Precision power conversion and data-center power supplies')],
'Software & applications':[('WDAY','Workday','Business applications and AI-assisted enterprise workflows'),('ZS','Zscaler','Cloud security for distributed workloads'),('PATH','UiPath','Enterprise automation and AI agents'),('AI','C3.ai','Enterprise AI application software'),('INFY','Infosys','Enterprise AI implementation and IT services')]
}.items():
 ROSTER.extend(dict(ticker=t,name=n,role=r,sector=sector) for t,n,r in rows)
for company in ROSTER:
 if company['ticker']=='WDC':company['sector']='Networking & servers'
